set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports Clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports Start]
set_property -dict {PACKAGE_PIN F13  IOSTANDARD LVCMOS33} [get_ports {Done}]
set_property -dict {PACKAGE_PIN J4   IOSTANDARD LVCMOS15} [get_ports {A[3]}]
set_property -dict {PACKAGE_PIN L3   IOSTANDARD LVCMOS15} [get_ports {A[2]}]
set_property -dict {PACKAGE_PIN K3   IOSTANDARD LVCMOS15} [get_ports {A[1]}]
set_property -dict {PACKAGE_PIN M2   IOSTANDARD LVCMOS15} [get_ports {A[0]}]
set_property -dict {PACKAGE_PIN J6   IOSTANDARD LVCMOS15} [get_ports {B[3]}]
set_property -dict {PACKAGE_PIN L5   IOSTANDARD LVCMOS15} [get_ports {B[2]}]
set_property -dict {PACKAGE_PIN L4   IOSTANDARD LVCMOS15} [get_ports {B[1]}]
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD LVCMOS33} [get_ports {B[0]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports {Sel[1]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports {Sel[0]}]
set_property -dict {PACKAGE_PIN D20  IOSTANDARD LVCMOS33} [get_ports {a_to_g[0]}]
set_property -dict {PACKAGE_PIN C20  IOSTANDARD LVCMOS33} [get_ports {a_to_g[1]}]
set_property -dict {PACKAGE_PIN C22  IOSTANDARD LVCMOS33} [get_ports {a_to_g[2]}]
set_property -dict {PACKAGE_PIN B22  IOSTANDARD LVCMOS33} [get_ports {a_to_g[3]}]
set_property -dict {PACKAGE_PIN B21  IOSTANDARD LVCMOS33} [get_ports {a_to_g[4]}]
set_property -dict {PACKAGE_PIN A21  IOSTANDARD LVCMOS33} [get_ports {a_to_g[5]}]
set_property -dict {PACKAGE_PIN E22  IOSTANDARD LVCMOS33} [get_ports {a_to_g[6]}]
set_property -dict {PACKAGE_PIN D22  IOSTANDARD LVCMOS33} [get_ports {a_to_g[7]}]
set_property -dict {PACKAGE_PIN E14  IOSTANDARD LVCMOS33} [get_ports {an[7]}]  
set_property -dict {PACKAGE_PIN E16  IOSTANDARD LVCMOS33} [get_ports {an[6]}]  
set_property -dict {PACKAGE_PIN D16  IOSTANDARD LVCMOS33} [get_ports {an[5]}]   
set_property -dict {PACKAGE_PIN D14  IOSTANDARD LVCMOS33} [get_ports {an[4]}]   
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports {an[3]}]   
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVCMOS33} [get_ports {an[2]}]  
set_property -dict {PACKAGE_PIN AA9  IOSTANDARD LVCMOS33} [get_ports {an[1]}]  
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports {an[0]}]   

set_property -dict {PACKAGE_PIN F21 IOSTANDARD LVCMOS33} [get_ports {Reset}] 

set_property SEVERITY{Warning}[get_drc_checks NSTD-1]
